### ISSUE TITLE
About testing samples for Snow100K

### ISSUE THREAD

**Issue by c-yn** [Ephemeral182/SnowFormer#1]
Dear author, thanks for your excellent work.

A quick question is how to sample 2000 images from Snow 100K testing set?

2000 images from each subset (S/M/L) and compute average, or mix 3 subsets and then select 2000 images randomly? 

Thanks for your reply.

**Comment by Ephemeral182** [comment]
For your question, we randomly sample a total of 2000 images from each subset (S/M/L) for testing, and the number of images from the S subset is more than the M and L ones. We will release the testing set after being accepted.
