### ISSUE TITLE
其他paper的结果

### ISSUE THREAD

**Issue by cs-hao** [Ephemeral182/SnowFormer#7]
作者，您好。我看你们的所有去雪任务的工作中，在其他方法上（例如NAFNet和Restormer等）的结果都是你们自己重新训练的，但是我在重新训练过程中，NAFNet的结果远高于你论文中的结果。我想知道这是怎么回事呢？

**Comment by Ephemeral182** [comment]
嗨您好,nafnet我并没有用他开源的配置,用的是小的那个block数量,他原版的参数量太多了
